---
- name: Prepare Hetzner Robot Mock API
  hosts: localhost
  tasks:
    - name: Run Hetzner Robot Mock API Container
      shell: docker run -d --rm --network molecule --name hetzner-robot {{ hetzner_vswitch_webservice_mock }}
    - name: Create vSwitch
      uri:
        url: "{{ hetzner_vswitch_webservice_base_url }}/vswitch"
        method: POST
        user: "{{ hetzner_vswitch_webservice_username }}"
        password: "{{ hetzner_vswitch_webservice_password }}"
        status_code: 201
        body:
          vlan: 4001
          name: Existing vSwitch
          cancelled: false
          server: []
        force_basic_auth: yes
        body_format: json

- name: Fetch package dependencies depending on the distribution
  hosts: platforms
  tasks:
    - debug:
        var: ansible_distribution
    - debug:
        var: ansible_distribution_major_version
    - include_vars: "{{ item }}"
      with_first_found:
        - "prepare-packages-{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version}}.yml"
        - "prepare-packages-{{ ansible_distribution | lower }}.yml"
        - "prepare-packages.yml"
      tags: vars

- name: Install package dependencies on platforms hosts
  hosts: platforms
  tasks:
    - name: Install required packages
      package:
        name: "{{ packages }}"
        state: present
